//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iToothServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacient_doctor
    {
        public int pacient_doctor_id { get; set; }
        public int pacient_id { get; set; }
        public int doctor_id { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual pacient pacient { get; set; }
    }
}
